import type { Config } from '@stencil/core';
import { reactOutputTarget } from '@stencil/react-output-target';

/**
 * udp-powerbi-visuals: the Univerus visuals as presentational web components, laid out like UDP's
 * udp-stencil-component-library (tags udp-pbi-*, one folder per component with its readme) so they
 * can be copied there once approved (see MIGRATION.md).
 *
 *  components/  custom elements for bundlers (what the React wrappers import)
 *  hydrate/     server-side renderer, used by the SSR smoke tests in Vitest
 *  docs/        components.json: tags, props and events, cross-checked against the manifest schema
 *  src/components/<family>/<tag>/readme.md  props, events and slots per component (docs-readme, as in UDP)
 *  ../../src/components/powerbi-visuals/generated  React 18 wrappers (@lit/react), regenerated on every build
 *
 * `empty: false`: a build overwrites its files in place instead of emptying the folder first.
 * `npm run dev` runs `stencil --watch` next to Vite (and an IDE may run `npm test`, which builds
 * too); an emptied folder made Vite fail with "Failed to resolve import" until the build finished.
 * Old hashed chunks (`p-*.js`) can linger; nothing imports them and the folder is ignored by git.
 */
export const config: Config = {
  namespace: 'udppowerbivisuals',
  srcDir: 'src',
  outputTargets: [
    {
      type: 'dist-custom-elements',
      dir: 'components',
      empty: false,
      externalRuntime: false,
      customElementsExportBehavior: 'single-export-module',
      generateTypeDeclarations: true,
    },
    { type: 'dist-hydrate-script', dir: 'hydrate', empty: false },
    { type: 'docs-json', file: 'docs/components.json' },
    { type: 'docs-readme', footer: '*Generated by Stencil from the component source. Do not edit by hand.*' },
    reactOutputTarget({
      outDir: '../../src/components/powerbi-visuals/generated',
      stencilPackageName: '@powerreact/udp-powerbi-visuals',
      customElementsDir: 'components',
    }),
  ],
  // The package is consumed from source through the workspace: no npm publishing checks
  validatePrimaryPackageOutputTarget: false,
};
